### PR TITLE
Make UserService backend runtime configurable: Fixes #1445

### LINKED ISSUE #1419: Team managers unable to add new users
**Describe the bug**

Team managers were able to create new users and add them to their respective teams. 

Since the change to the security model, adding a new user adds the user to the `userinfo` table, but does not add the user to the keycloak instance. 

As a result, Team managers are no longer able to manage their team without assistance from an administrator

### LINKED ISSUE #1445: NPE calling io.quarkus.security.identity.SecurityIdentity.getRoles()
**Describe the bug**

When the config option `horreum.roles.provider=keycloak` is set, the following exception is thrown when a user attempts to log in:

```
2024-03-07 12:21:40,653 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-2) HTTP Request to /api/user/roles failed, error id: 658e1b00-c98d-4618-b168-d316ddaab9e1-3: java.lang.NullPointerException: Cannot invoke "io.quarkus.security.identity.SecurityIdentity.getRoles()" because "this.identity" is null
	at io.hyperfoil.tools.horreum.svc.UserServiceImpl.getRoles(UserServiceImpl.java:69)
	at io.hyperfoil.tools.horreum.api.internal.services.UserService$quarkusrestinvoker$getRoles_34a90be96945d58693e1819e1692bb3a3951fdd3.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by johnaohara**
## Fixes Issue

Fixes #1445 
Fixes #1419

This PR makes the UserService "backend" (keycloak/database) runtime configurable; 

- The same property selects the backend, but is resolved at runtime not build time. We only have to build one image 
- defaults back to keycloak behaviour - the upgrade from keycloak to database will be an admin choice
- there is an additional check for migration, that the database backend has been selected AND the tables are empty
- prevents a "split-mode" - Fixes #1419

Once migrated from keycloak -> database, everything continues to function with the roles resolved from the database

### CODE REVIEW

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java [hunk 1]
```diff
@@ -1,66 +1,34 @@
...
-
    @Inject
    SecurityIdentity identity;
 
    @Inject
-   Vertx vertx;
+   Instance<UserBackEnd> backend;
 
-   private static UserData toUserInfo(UserRepresentation rep) {
+   public static UserData toUserInfo(UserRepresentation rep) {
```
Comment (barreiro) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java:31]: this `toUserInfo` implementation can be moved to keycloak backend and kept private

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java [hunk 2]
```diff
@@ -27,46 +25,37 @@
...
+      return new UserService.UserData("", info.username, info.fistName, info.lastName, info.email);
    }
 
-   @Authenticated
-   @Override public List<String> getRoles() {
-      return identity.getRoles().stream().toList();
-   }
-
-   @Authenticated
-   @WithRoles(extras = Roles.HORREUM_SYSTEM)
```
Comment (barreiro) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java:53]: need to keep `@WithRoles` annotation because of row level security

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java [hunk 3]
```diff
@@ -27,46 +25,37 @@
...
-   @Override public List<UserData> searchUsers(String query) {
+   @Override public List<UserService.UserData> searchUsers(String query) {
       List<UserInfo> users = UserInfo.list("username like ?1", "%" + query + "%");
-      return users.stream().map(DatabaseUserServiceImpl::toUserInfo).collect(toList());
+      return users.stream().map(DatabaseUserBackend::toUserInfo).collect(toList());
    }
 
-   @WithRoles(extras = Roles.HORREUM_SYSTEM)
```
Comment (barreiro) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java:59]: need to keep `@WithRoles` annotation because of row level security

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java [hunk 4]
```diff
@@ -104,43 +93,21 @@ private static UserData toUserInfo(UserInfo info) {
...
+   private void addTeamMembership(UserInfo userInfo, String teamName, TeamRole role) {
+      Optional<Team> storedTeam = Team.find("teamName", teamName).firstResultOptional();
+      userInfo.teams.add(new TeamMembership(userInfo, storedTeam.orElseGet(() -> Team.getEntityManager().merge(new Team(teamName))), role));
+   }
    @Override public List<String> getTeams() {
       List<Team> teams = Team.listAll();
       return teams.stream().map(t -> t.teamName + "-team").collect(toList());
    }
-
-   @WithRoles(addUsername = true)
```
Comment (barreiro) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java:124]: need to keep `@WithRoles` annotation because of row level security

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java [hunk 5]
```diff
@@ -104,43 +93,21 @@ private static UserData toUserInfo(UserInfo info) {
...
-   @Transactional
-   @WithRoles(addUsername = true)
-   @Override public void setDefaultTeam(String team) {
-      UserInfo userInfo = UserInfo.findById(identity.getPrincipal().getName());
-      userInfo.defaultTeam = Util.destringify(team);
-      userInfo.persistAndFlush();
-   }
-
-   @Authenticated
-   @WithRoles(extras = Roles.HORREUM_SYSTEM)
```
Comment (barreiro) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java:139]: need to keep `@WithRoles` annotation because of row level security

File: horreum-web/package-lock.json [hunk 6]
```diff
@@ -1797,9 +1797,9 @@
       }
     },
     "node_modules/caniuse-lite": {
-      "version": "1.0.30001594",
-      "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001594.tgz",
-      "integrity": "sha512-VblSX6nYqyJVs8DKFMldE2IVCJjZ225LW00ydtUWwh5hk9IfkTOffO6r8gJNsH0qqqeAF8KrbMYA2VEwTlGW5g==",
+      "version": "1.0.30001596",
```
Comment (barreiro) [inline horreum-web/package-lock.json:1800]: let's keep changes to package-lock out of this PR

**Review by barreiro — CHANGES_REQUESTED** [review]
There are some missing `@RolesAllowed` in the database implementation to deal with row level security.

**Comment by johnaohara** [comment]
@barreiro I thought I had reinstated all the roles annotations i probably have a commit i haven't pushed.  I will fix it when I get back in front of my machine

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java (hunk 2 above)
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java:53]: Reinstated @WithRoles

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java (hunk 3 above)
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java:59]: Reinstated @WithRoles

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java (hunk 4 above)
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/user/DatabaseUserBackend.java:124]: This method is still implemented in `UserServiceImpl` and has the `@WithRoles` annotation

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java (hunk 1 above)
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/UserServiceImpl.java]: Have reinstated in KeycloakUserBackend

File: horreum-web/package-lock.json (hunk 6 above)
Comment (johnaohara) [reply horreum-web/package-lock.json]: I have removed package-lock.json from the PR

**Review by barreiro — APPROVED** [review]
