### PR TITLE
Strongly typed Datastore configuration - Fixes #2088

### LINKED ISSUE #2088: Elasticsearch configuration always requires credentials
**Describe the bug**

The elasticsearch datastore always requires credential configured. for insecure instances, where there are no credentials required, the credential validation fails when a new ES datastore is configured

### PR DESCRIPTION
**Pull request by johnaohara**
This is a fairly major re-factor of the `Datastore` configuration API.

It solves the following problems;

- Add Strongly Typed authentication models: `No Auth`, `Api Key` and `Username/Password`
- Add openapi discriminators for datastore authentication types
- Fixes validation for all datastores: Fixes #2088 
- UI dynamically displays auth properties based on available auth types and user selected auth type
- Add validation of authentication when updated existing datastores

### CODE REVIEW

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java [hunk 1]
```diff
@@ -3,26 +3,30 @@
...
     @Override
     public String validateConfig() {
-        if ("".equals(apiKey)) {
-            return "apiKey must be set";
-        }
-        if ("".equals(url)) {
-            return "url must be set";
+        if (authentication instanceof APIKeyAuth) {
+            APIKeyAuth apiKeyAuth = (APIKeyAuth) authentication;
+            if ("".equals(apiKeyAuth.apiKey)) {
```
Comment (stalep) [inline horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java:27]: I assume apiKey can never be null since it's required?

File: horreum-web/src/domain/admin/Datastores.tsx [hunk 2]
```diff
@@ -3,9 +3,15 @@ import {useContext, useEffect, useState} from "react"
...
-import TeamSelect, {Team, SHOW_ALL} from "../../components/TeamSelect"
+import TeamSelect, {Team, SHOW_ALL, createTeam} from "../../components/TeamSelect"
 
 
+const newBackendConfig: ElasticsearchDatastoreConfig | CollectorApiDatastoreConfig = {
+    url: "",
+    builtIn: false,
+    authentication: { 'type': 'none' }
+}
+
```
Comment (barreiro) [inline horreum-web/src/domain/admin/Datastores.tsx:14]: move out of the import section

File: horreum-web/src/domain/admin/Datastores.tsx [hunk 3]
```diff
@@ -51,73 +59,23 @@ const DatastoresTable = ( props: dataStoreTableProps) => {
...
-    const newDatastore = () => {
-        setDatastore(newDataStore)
-        setEditModalOpen(!editModalOpen);
-    };
-
 
     return (
-
-        <Stack hasGutter>
-            <StackItem>
```
Comment (barreiro) [inline horreum-web/src/domain/admin/Datastores.tsx:120]: fix indentation level

**Review by barreiro — CHANGES_REQUESTED** [review]
I added several comments to the code, but overall looks good.

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java (hunk 1 above)
Comment (johnaohara) [reply horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java:27]: If the user has selected "api-key" as the authentication method, then the apiKey can not be empty or null. Otherwise the user should select the "none" authentication model.

However, the api is not checking for null here, just zero length string. There should also be a check for null

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java [hunk 4]
```diff
@@ -3,26 +3,30 @@
...
+                return "url must be set";
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java:28]: good catch

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/DatastoreType.java [hunk 5]
```diff
@@ -37,4 +53,25 @@ public static DatastoreType fromString(String str) {
             return DatastoreType.valueOf(str);
         }
     }
+
+    public TypeConfig getConfig() {
+        return new TypeConfig(this, name, label, buildIn, supportedAuths);
+    }
+
+    public class TypeConfig {
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/DatastoreType.java:61]: good catch

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java [hunk 6]
```diff
@@ -32,6 +30,12 @@ public class ConfigServiceImpl implements ConfigService {
 
     private static final Logger log = Logger.getLogger(ConfigServiceImpl.class);
 
+    //cache available dataStore configurations
+    private static final List<DatastoreType.TypeConfig> datastoreTypes = Arrays.asList(
+            DatastoreType.values()).stream()
+            .map(type -> type.getConfig())
+            .collect(Collectors.toList());
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java:37]: Definitely easier to read :)

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java [hunk 7]
```diff
@@ -144,18 +153,36 @@ public Integer newDatastore(Datastore datastore) {
...
+        if (datastoreImpl == null) {
+            throw ServiceException.badRequest("Unknown datastore type: " + datastore.type);
+        }
+
+        String error = datastoreImpl.validateConfig(datastore.config);
+
+        if (error != null) {
+            throw ServiceException.badRequest(error);
+        }
+
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ConfigServiceImpl.java:185]: Done

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java [hunk 8]
```diff
@@ -159,7 +172,10 @@ public UploadType uploadType() {
     @Override
     public String validateConfig(Object config) {
         try {
-            return mapper.treeToValue((ObjectNode) config, CollectorApiDatastoreConfig.class).validateConfig();
+            CollectorApiDatastoreConfig collectorApiDatastoreConfig = mapper.treeToValue((ObjectNode) config,
+                    CollectorApiDatastoreConfig.class);
+            return collectorApiDatastoreConfig.validateConfig();
+
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java:178]: done

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java [hunk 9]
```diff
@@ -93,9 +96,17 @@ private static void verifyPayload(ObjectMapper mapper, CollectorApiDatastoreConf
         // Verify that the tag is in the distinct list of tags
         URI tagsUri = URI.create(jsonDatastoreConfig.url + "/tags/distinct");
         HttpRequest.Builder tagsBuilder = HttpRequest.newBuilder().uri(tagsUri);
-        HttpRequest tagsRequest = tagsBuilder
-                .header("Content-Type", "application/json")
-                .header("token", jsonDatastoreConfig.apiKey).build();
+        HttpRequest tagsRequest = null;
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java:99]: done

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java:178]: I have changed this back, it was left-over from some other re-factoring that I reverted.

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java [hunk 10]
```diff
@@ -67,18 +66,27 @@ public DatastoreResponse handleRun(JsonNode payload,
...
+
+                    APIKeyAuth apiKeyAuth = (((APIKeyAuth) elasticsearchDatastoreConfig.authentication));
+
                     builder.setDefaultHeaders(new Header[] {
-                            new BasicHeader("Authorization", "ApiKey " + elasticsearchDatastoreConfig.apiKey)
+                            new BasicHeader("Authorization", "ApiKey " + apiKeyAuth.apiKey)
                     });
-                } else {
+
+                } else if (elasticsearchDatastoreConfig.authentication instanceof PasswordAuthentication) {
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java:78]: thanks

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java [hunk 11]
```diff
@@ -246,7 +256,9 @@ public UploadType uploadType() {
     @Override
     public String validateConfig(Object config) {
         try {
-            return mapper.treeToValue((ObjectNode) config, ElasticsearchDatastoreConfig.class).validateConfig();
+            ElasticsearchDatastoreConfig datastoreConfig = mapper.treeToValue((ObjectNode) config,
+                    ElasticsearchDatastoreConfig.class);
+            return datastoreConfig.validateConfig();
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/ElasticsearchDatastore.java:261]: reverted

File: horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx [hunk 12]
```diff
@@ -9,84 +9,141 @@ import {
...
+    const [authOptions, setAuthOptions] = useState<Array<string>>( []);
 
-    const handleOptionChange = (_event: React.FormEvent<HTMLSelectElement>, value: string) => {
-        const option: datastoreOption | undefined = options.filter( optionvalue => optionvalue.value === value).pop()
-        if ( option ){
-            setEnableUrl(option.urlDisabled)
-            setEnableToken(option.tokenDisbaled)
+    useEffect(() => { //find initial auth options for the selected datastore
+        const typeConf = dataStoreTypes.filter( optionvalue => optionvalue.enumName === dataStore.type).pop()
+        setAuthOptions(typeConf?.supportedAuths || [])
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx:117]: This helped while debugging, having a local variable on the stack to inspect. but can remove the allocation

File: horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx [hunk 13]
```diff
@@ -9,84 +9,141 @@ import {
...
+    }, [dataStore]);
 
-            updateDatastore({...dataStore, type: option.value})
+    const handleOptionChange = (_event: React.FormEvent<HTMLSelectElement>, value: string) => {
+        const selectedOption: TypeConfig | undefined = dataStoreTypes.filter( optionvalue => optionvalue.enumName === value).pop()
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx:121]: updated

File: horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx [hunk 14]
```diff
@@ -9,84 +9,141 @@ import {
...
+type UpdateDatastoreProps = {
+    dataStore: Datastore
+    updateDatastore(datastore: Datastore): void
+}
+function NoAuth () {
+    return (<div></div>)
+}
+function UsernameAuth ({dataStore, updateDatastore} : UpdateDatastoreProps) {
+    return  (
+        <div>
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx:38]: updated

File: horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx [hunk 15]
```diff
@@ -9,84 +9,141 @@ import {
...
+            </FormHelperText>
+        </FormGroup>
+        </div>
+    )
+}
+
+function ApiKeyAuth ({dataStore, updateDatastore} : UpdateDatastoreProps){
+    return  (
+        <div>
+            <FormGroup
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx:86]: have added `isRequired` to the api text input

File: horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx [hunk 16]
```diff
@@ -9,84 +9,141 @@ import {
...
+                    <HelperTextItem>Please provide a Username to authenticate against datastore</HelperTextItem>
+                </HelperText>
+            </FormHelperText>
+        </FormGroup>
+        <FormGroup
+            label="Password"
+            fieldId="horizontal-form-token"
+        >
+            <TextInput
+                value={ (dataStore.config.authentication as UsernamePassAuth).password } //"password" in dataStore.config ? dataStore.config.password : ""}
```
[the remark this answers is not in the document]
Comment (johnaohara) [reply horreum-web/src/domain/admin/datastore/ModifyDatastoreModal.tsx:64]: removed comments

File: horreum-web/src/domain/admin/Datastores.tsx (hunk 3 above)
Comment (johnaohara) [reply horreum-web/src/domain/admin/Datastores.tsx:120]: This refers to a line that has been removed, but I am applied auto formatting to the entire file

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java [hunk 17]
```diff
@@ -3,26 +3,30 @@
 import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
 import org.eclipse.microprofile.openapi.annotations.media.Schema;
 
+import io.hyperfoil.tools.horreum.api.data.datastore.auth.APIKeyAuth;
+import io.hyperfoil.tools.horreum.api.data.datastore.auth.NoAuth;
+
 @Schema(type = SchemaType.OBJECT, required = true, description = "Type of backend datastore")
 public class CollectorApiDatastoreConfig extends BaseDatastoreConfig {
 
+    public static final String[] auths = { NoAuth._TYPE, APIKeyAuth._TYPE };
```
Comment (barreiro) [inline horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java:12]:
```suggestion
```

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java [hunk 18]
```diff
@@ -3,26 +3,30 @@
...
     @Override
     public String validateConfig() {
-        if ("".equals(apiKey)) {
-            return "apiKey must be set";
-        }
-        if ("".equals(url)) {
-            return "url must be set";
+        if (authentication instanceof APIKeyAuth) {
+            APIKeyAuth apiKeyAuth = (APIKeyAuth) authentication;
+            if ("".equals(apiKeyAuth.apiKey) || apiKeyAuth.apiKey == null) {
```
Comment (barreiro) [inline horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java:27]:
```suggestion
            if (apiKeyAuth.apiKey == null || apiKeyAuth.apiKey.isEmpty()) {
```

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java [hunk 19]
```diff
@@ -1,62 +1,44 @@
...
-import com.fasterxml.jackson.annotation.JsonIgnore;
-import com.fasterxml.jackson.annotation.JsonProperty;
+import io.hyperfoil.tools.horreum.api.data.datastore.auth.APIKeyAuth;
+import io.hyperfoil.tools.horreum.api.data.datastore.auth.NoAuth;
+import io.hyperfoil.tools.horreum.api.data.datastore.auth.UsernamePassAuth;
 
 @Schema(type = SchemaType.OBJECT, required = true, description = "Type of backend datastore")
 public class ElasticsearchDatastoreConfig extends BaseDatastoreConfig {
 
+    public static final String[] auths = { NoAuth._TYPE, APIKeyAuth._TYPE, UsernamePassAuth._TYPE };
```
Comment (barreiro) [inline horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java:13]:
```suggestion
```

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java [hunk 20]
```diff
@@ -1,62 +1,44 @@
...
+    public static final String name = "Elasticsearch";
+    public static final String label = "Elasticsearch";
+    public static final Boolean builtIn = false;
```
Comment (barreiro) [inline horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java:16]:
```suggestion
```

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java [hunk 21]
```diff
@@ -3,26 +3,30 @@
...
+import io.hyperfoil.tools.horreum.api.data.datastore.auth.APIKeyAuth;
+import io.hyperfoil.tools.horreum.api.data.datastore.auth.NoAuth;
+
 @Schema(type = SchemaType.OBJECT, required = true, description = "Type of backend datastore")
 public class CollectorApiDatastoreConfig extends BaseDatastoreConfig {
 
+    public static final String[] auths = { NoAuth._TYPE, APIKeyAuth._TYPE };
+    public static final String name = "Collectorapi";
+    public static final String label = "Collector API";
+    public static final Boolean builtIn = false;
```
Comment (barreiro) [inline horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java:15]:
```suggestion
```

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java [hunk 22]
```diff
@@ -3,9 +3,20 @@
 import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
 import org.eclipse.microprofile.openapi.annotations.media.Schema;
 
+import io.hyperfoil.tools.horreum.api.data.datastore.auth.NoAuth;
+
 @Schema(type = SchemaType.OBJECT, required = true, description = "Built in backend datastore")
 public class PostgresDatastoreConfig extends BaseDatastoreConfig {
 
+    public static final String[] auths = { NoAuth._TYPE };
```
Comment (barreiro) [inline horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java:11]:
```suggestion
```

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java [hunk 23]
```diff
@@ -3,9 +3,20 @@
...
+    public static final String name = "Postgres";
+    public static final String label = "Postgres";
+    public static final Boolean builtIn = true;
```
Comment (barreiro) [inline horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java:14]:
```suggestion
```

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java [hunk 24]
```diff
@@ -1,62 +1,44 @@
...
+        if (authentication instanceof APIKeyAuth) {
+            APIKeyAuth apiKeyAuth = (APIKeyAuth) authentication;
+            if ("".equals(apiKeyAuth.apiKey)) {
+                return "apiKey must be set";
+            }
+        } else if (authentication instanceof UsernamePassAuth) {
+            UsernamePassAuth usernamePassAuth = (UsernamePassAuth) authentication;
+
+            if (usernamePassAuth.username == null || usernamePassAuth.password == null
+                    || "".equals(usernamePassAuth.username) || "".equals(usernamePassAuth.password)) {
```
Comment (barreiro) [inline horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java:38]:
```suggestion
            if (usernamePassAuth.username == null || usernamePassAuth.username.isEmpty()
                    || usernamePassAuth.password == null || usernamePassAuth.password.isEmpty()) {
```

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java [hunk 25]
```diff
@@ -1,62 +1,44 @@
...
-        String _apiKey = requireNonNullElse(apiKey, "");
-        String _username = requireNonNullElse(username, "");
-        String _password = requireNonNullElse(password, "");
-
-        if ("".equals(_apiKey) && ("".equals(_username) || "".equals(_password))) {
-            return "Either apiKey or username and password must be set";
+        //TODO:: replace with pattern matching after upgrading to java 17
+        if (authentication instanceof APIKeyAuth) {
+            APIKeyAuth apiKeyAuth = (APIKeyAuth) authentication;
+            if ("".equals(apiKeyAuth.apiKey)) {
```
Comment (barreiro) [inline horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java:31]:
```suggestion
            if (apiKeyAuth.apiKey == null || apiKeyAuth.apiKey.isEmpty()) {
```

**Review by barreiro — CHANGES_REQUESTED** [review]
Added some suggestions for more cleanup on the API module

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java (hunk 19 above)
Comment (johnaohara) [reply horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java:13]: This is accessed via reflection: https://github.com/Hyperfoil/Horreum/pull/2223/files#diff-8a4bd7c5a2730d0b066069e4fe1d81fd44eb3c7f84b69867ad74b83f74aca8deR27-R30

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java (hunk 20 above)
Comment (johnaohara) [reply horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java:16]: This is accessed via reflection: https://github.com/Hyperfoil/Horreum/pull/2223/files#diff-8a4bd7c5a2730d0b066069e4fe1d81fd44eb3c7f84b69867ad74b83f74aca8deR27-R30

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java (hunk 21 above)
Comment (johnaohara) [reply horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java:15]: This is accessed via reflection: https://github.com/Hyperfoil/Horreum/pull/2223/files#diff-8a4bd7c5a2730d0b066069e4fe1d81fd44eb3c7f84b69867ad74b83f74aca8deR27-R30

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java (hunk 22 above)
Comment (johnaohara) [reply horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/PostgresDatastoreConfig.java:11]: This is accessed via reflection: https://github.com/Hyperfoil/Horreum/pull/2223/files#diff-8a4bd7c5a2730d0b066069e4fe1d81fd44eb3c7f84b69867ad74b83f74aca8deR27-R30

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java (hunk 25 above)
Comment (johnaohara) [reply horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java:31]: Thanks for catching this

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java (hunk 18 above)
Comment (johnaohara) [reply horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/CollectorApiDatastoreConfig.java:27]: will change to `isBlank()` to take into account white-space as well

File: horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java (hunk 24 above)
Comment (johnaohara) [reply horreum-api/src/main/java/io/hyperfoil/tools/horreum/api/data/datastore/ElasticsearchDatastoreConfig.java:38]: will change to `isBlank()` to take into account white-space as well

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java [hunk 26]
```diff
@@ -93,10 +96,17 @@ private static void verifyPayload(ObjectMapper mapper, CollectorApiDatastoreConf
...
+
+        if (jsonDatastoreConfig.authentication instanceof APIKeyAuth) {
+            tagsBuilder
+                    .header("Content-Type", "application/json")
+                    .header("token", ((APIKeyAuth) jsonDatastoreConfig.authentication).apiKey);
+        } else {
+            tagsBuilder
+                    .header("Content-Type", "application/json");
+
+        }
```
Comment (lampajr) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java:108]: This could be simplified as we are setting `application/json` on both cases
```suggestion
        tagsBuilder
                .header("Content-Type", "application/json");
        if (jsonDatastoreConfig.authentication instanceof APIKeyAuth) {
            tagsBuilder
                    .header("token", ((APIKeyAuth) jsonDatastoreConfig.authentication).apiKey);
        }
```

**Review by lampajr — APPROVED** [review]
LGTM!

I added just a minor comment, up to you to include it or not as it would be just a simplification 🚀

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java (hunk 26 above)
Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/datastore/CollectorApiDatastore.java]: Done, thanks

**Comment by barreiro** [comment]
I think this one is good to go.
