### PR TITLE
Import Test change detection variable fixes.

### LINKED ISSUE #1740: Import a Test with new Change Detection variable definitions are ignored by the import.
**Describe the bug**

New variables are ignored when the Test is imported.

**To Reproduce**

Create a test.
Export
Add change detection variable to the Test JSON definition
Import Test using JSON definition
Check for the new variable

**Version**

```
0.13.0
```

**Java**

```
17
```

### PR DESCRIPTION
**Pull request by whitingjr**
Added testcase to flush out defect when importing an existing Test with new definitions of Change Detection variables. Added fixes to add new variables.

## Fixes Issue

fixes #1740 

## Changes proposed

[x] - Allow more situation when a Test fields are updated

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] All new and existing tests passed.

### CODE REVIEW

File: horreum-backend/src/test/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapperTest.java
Comment (johnaohara) [inline horreum-backend/src/test/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapperTest.java:1]: I don't think we want to support the use case in this test. 

When importing we want to map to an existing TestDao, not create a new one, otherwise we will find ourselves in the situation where random Tests are created if there is an error in an import definition

**Review by johnaohara — CHANGES_REQUESTED** [review]
The title of this PR is refers to "change detection variable fixes", but also contains changes for Experiment Profile.

I think there are issues with the `ExperimentProfileMapperTest` testcase, can you update `testImportTestWithChangeDetectionVariable()` to verify the ExperimentProfile import as well, and change the test name to reflect. 

Please update the Issue/PR title to reflect that this also covers ExperimentProfile

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java [hunk 1]
```diff
@@ -217,6 +218,7 @@ void exportTest(TestExport test) {
         subscriptionService.exportSubscriptions(test);
     }
 
+    @WithRoles
```
[the remark this answers is not in the document]
Comment (whitingjr) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java:221]: your right, now removed

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapper.java [hunk 2]
```diff
@@ -48,7 +49,10 @@ public static ExperimentProfileDAO to(ExperimentProfile dto) {
         ep.selectorFilter = dto.selectorFilter;
 
         ep.comparisons = dto.comparisons.stream().map(ExperimentProfileMapper::toExperimentComparison).collect(Collectors.toList());
-
+        TestDAO test = new TestDAO();
+        if (dto.testId != null)
+            test.id = dto.testId;
+        ep.test = test;
```
[the remark this answers is not in the document]
Comment (whitingjr) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapper.java:55]: Thanks for highlighting that use of getting the reference.

**Comment by whitingjr** [comment]
> can you update testImportTestWithChangeDetectionVariable() to verify the ExperimentProfile import as well, and change the test name to reflect.
 Sure, this has been updated.

File: horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java [hunk 3]
```diff
@@ -691,6 +696,29 @@ public void testPagination() {
       assertEquals(0, listing.tests.size());
    }
 
+   @org.junit.jupiter.api.Test
+   public void testImportTestWithChangeDetectionVariable() {
+      Path p = new File(getClass().getClassLoader().getResource(".").getPath()).toPath();
+      p = p.getParent().getParent().getParent().resolve("infra-legacy/example-data/");
```
[the remark this answers is not in the document]
Comment (whitingjr) [reply horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/TestServiceTest.java:702]: I will rework the code.

File: horreum-backend/src/test/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapperTest.java
Comment (whitingjr) [reply horreum-backend/src/test/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapperTest.java:1]: Removed.

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java [hunk 4]
```diff
@@ -11,6 +11,7 @@
 import io.hyperfoil.tools.horreum.bus.AsyncEventChannels;
 import io.hyperfoil.tools.horreum.entity.data.ActionDAO;
 import io.hyperfoil.tools.horreum.events.DatasetChanges;
+import io.hyperfoil.tools.horreum.server.WithRoles;
```
Comment (johnaohara) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java:14]: Can we remove this unused import

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapper.java [hunk 5]
```diff
@@ -48,7 +54,10 @@ public static ExperimentProfileDAO to(ExperimentProfile dto) {
         ep.selectorFilter = dto.selectorFilter;
 
         ep.comparisons = dto.comparisons.stream().map(ExperimentProfileMapper::toExperimentComparison).collect(Collectors.toList());
-
+        if (dto.testId != null) {
+            em = Arc.container().instance(EntityManagerProvider.class).get().getEntityManager();
+            ep.test = em.getReference(TestDAO.class, dto.testId);
+        }
```
Comment (johnaohara) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapper.java:60]: The mappers are static property mappers, relationships between entities should be performed within the managed beans.

The custom `EntityManagerProvider` should be removed and instead a single line in `ExperimentServiceImpl.importTest()` on line 313 should be added;

```
profile.test = em.getReference(TestDAO.class, ep.testId);
```

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapper.java [hunk 6]
```diff
@@ -4,11 +4,17 @@
...
+import io.hyperfoil.tools.horreum.server.EntityManagerProvider;
+import io.quarkus.arc.Arc;
+import jakarta.persistence.EntityManager;
 
 import java.util.stream.Collectors;
 
 public class ExperimentProfileMapper {
 
+    private static EntityManager em;
+
```
Comment (johnaohara) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapper.java:17]: this should not be a static field in this class

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/EntityManagerProvider.java
Comment (johnaohara) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/EntityManagerProvider.java:1]: We don't need this custom provider

**Review by johnaohara — CHANGES_REQUESTED** [review]

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java (hunk 4 above)
Comment (whitingjr) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/ServiceMediator.java:14]: done

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapper.java (hunk 5 above)
Comment (whitingjr) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/mapper/ExperimentProfileMapper.java:60]: sure

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/EntityManagerProvider.java
Comment (whitingjr) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/server/EntityManagerProvider.java:1]: sure

**Comment by whitingjr** [comment]
@johnaohara Changes done.

**Review by johnaohara — APPROVED** [review]
LGTM! Thanks
