### PR TITLE
Validate test/schema import format: Fixes #1685

### LINKED ISSUE #1685: Schema and Test import do not validate structure of JSON passed into API
**Describe the bug**

When a schema or test is imported, the mapping of json to the import configuration object(s) is not validated, allowing incorrectly structured JSON to be processed for import.

This was one part of the issue that lead to: https://github.com/Hyperfoil/Horreum/issues/1661

### PR DESCRIPTION
**Pull request by johnaohara**
## Fixes Issue
Fixes #1685

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java [hunk 1]
```diff
@@ -849,7 +854,17 @@ public SchemaExport exportSchema(int id) {
    @Transactional
    @Override
    public void importSchema(ObjectNode node) {
-      SchemaExport importSchema = Util.OBJECT_MAPPER.convertValue(node, SchemaExport.class);
+      SchemaExport importSchema;
+
+      ObjectMapper customMapper = mapper.copy();
+      customMapper.enable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
```
Comment (lampajr) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java:860]: Can we create this additional mapper only once and then simply inject this mapper? Otherwise we are going to create `mapper.copy();` every time we need to import something

Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java:860]: I did think about that, but i was being lazy ;) thinking that importing schema/test is not on the hot path

Comment (lampajr) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/SchemaServiceImpl.java:860]: yeah, that's true.. I was thinking the same

**Review by lampajr — APPROVED** [review]

**Comment by johnaohara** [comment]
@lampajr I just pushed another commit that produces a custom mapper, which is cached and reused as a CDI bean by default: https://github.com/Hyperfoil/Horreum/pull/1689/commits/7463f9409a65b6234d9f8cdc9474d99c42ae1215

**Review by lampajr — APPROVED** [review]
> @lampajr I just pushed another commit that produces a custom mapper, which is cached and reused as a CDI bean by default: [7463f94](https://github.com/Hyperfoil/Horreum/commit/7463f9409a65b6234d9f8cdc9474d99c42ae1215)

Thanks @johnaohara , lgtm!
