### PR TITLE
Clear selected rows after Deletion of a row. fixes #957

### LINKED ISSUE #957: Selected runs change when deleting items
**Describe the bug**

In the Runs view, if you have an item or items selected with the left check boxes, and then you delete any one of the items using the right-side dialog drop-down, when the page refreshes, you may have different items selected. The selection seems to shift down to the next item in the list.

**Version**

Hosted 0.10.5
**OS**

Fedora 39

**Browser**

Brave

### PR DESCRIPTION
**Pull request by whitingjr**
## Fixes Issue

fixes #957 

## Changes proposed

[x] - Clear any selection of rows when a row has been deleted

[ ] - Not correct; marked as **not** done-->

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

File: horreum-web/src/domain/runs/components.tsx [hunk 1]
```diff
@@ -160,14 +160,15 @@ function useUpdateDescription(run: RunSummary): MenuItem<RunSummary> {
     ]
 }
 
-export function Menu(run: RunSummary, refreshCallback: () => void) {
+export function Menu(run: RunSummary, refreshCallback: () => void, clearSelected: Function) {
```
Comment (johnaohara) [inline horreum-web/src/domain/runs/components.tsx:163]: please define the `clearSelected` function in the same way as the `refreshCallback` function is defined, i.e. `clearSelected: () => void` that way it is clear what the expected args and and the return type

The function name should reflect that it is a callback as well, so maybe rename to `clearCallback`

**Review by johnaohara — CHANGES_REQUESTED** [review]

File: horreum-web/src/domain/runs/components.tsx (hunk 1 above)
Comment (whitingjr) [reply horreum-web/src/domain/runs/components.tsx:163]: ok

File: horreum-web/src/domain/runs/components.tsx [hunk 2]
```diff
@@ -160,14 +160,15 @@ function useUpdateDescription(run: RunSummary): MenuItem<RunSummary> {
...
     const { alerting } = useContext(AppContext) as AppContextType;
 
     const changeAccess = useChangeAccess({
         onAccessUpdate: (id, owner, access) => updateRunAccess(id, run.testid, owner, access, alerting).then(refreshCallback),
     })
     const del = useDelete({
-        onDelete: id => trash(alerting, id, run.testid).then(refreshCallback),
+        onDelete: id => trash(alerting, id, run.testid).then(refreshCallback)
+            .then(clearSelected()),
```
[the remark this answers is not in the document]
Comment (whitingjr) [reply horreum-web/src/domain/runs/components.tsx:171]: ok

**Review by johnaohara — APPROVED** [review]
