### PR TITLE
Changed default ordering to Decending and preserve ordering of DTOs. 

### LINKED ISSUE #929: Default sort of runs/datasets are not by newest first
**Describe the bug**

The runs and datasets are no longer sorted by newest on top by default. It seems to be oldest first  on a page by page basis.

**To Reproduce**

Go to a test run list and the items are not sorted by newest first.

**Version**
0.10.4

### PR DESCRIPTION
**Pull request by whitingjr**
Preserves DTO object ordering to UI.

## Fixes Issue

 fixes #929  issue

## Changes proposed

[x] - Add testcase to check Runs ordering in ASC or DESC mode.
[x] - Add testcase to check Datasets ordering in ASC or default DESC mode.
[x] - Fix the default ordering to Descending
[x] - Fixs the loss of ordering when creating a list of DTO objects

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java [hunk 1]
```diff
@@ -752,7 +752,8 @@ public RunsSummary listAllRuns(String query, boolean matchAll, String roles, boo
          RunsSummary summary = new RunsSummary();
          // TODO: total does not consider the query but evaluating all the expressions would be expensive
          summary.total = trashed ? RunDAO.count() : RunDAO.count("trashed = false");
-         summary.runs = runs.stream().map(this::createSummary).collect(Collectors.toList());
+         summary.runs = new ArrayList<>(runs.size());
+         runs.forEach(r -> summary.runs.add(createSummary(r)));
```
Comment (johnaohara) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java:756]: please can we leave the original implementation. Its execution was parallelizable and the code is more readable

Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/RunServiceImpl.java:756]: @whitingjr please can you take a look at this

**Review by stalep — APPROVED** [review]
