### PR TITLE
Fix ChangeDetection additions.

### LINKED ISSUE #1124: Entity persistence mode type persist causes PersistentObjectException.
**Describe the bug**

When a Variable is being persisted it is causing an error.

```
2024-01-19 15:15:54,580 ERROR [io.hyp.too.hor.svc.AlertingServiceImpl] (executor-thread-1395) Failed to update variables: org.hibernate.PersistentObjectException: detached entity passed to persist: io.hyperfoil.tools.horreum.entity.alerting.ChangeDetectionDAO
	at org.hibernate.event.internal.DefaultPersistEventListener.persist(DefaultPersistEventListener.java:88)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:77)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:54)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:755)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:739)
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.persist(TransactionScopedSession.java:145)
	at org.hibernate.engine.spi.SessionLazyDelegator.persist(SessionLazyDelegator.java:275)
	at org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_ClientProxy.persist(Unknown Source)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:101)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:96)
	at io.quarkus.hibernate.orm.panache.PanacheEntityBase.persist(PanacheEntityBase.java:53)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.lambda$updateVariables$40(AlertingServiceImpl.java:754)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.updateCollection(AlertingServiceImpl.java:809)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.lambda$updateVariables$42(AlertingServiceImpl.java:749)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.updateCollection(AlertingServiceImpl.java:804)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.updateVariables(AlertingServiceImpl.java:731)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl_Subclass.updateVariables$$superforward(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl_Subclass$$function$$30.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor.intercept(RolesInterceptor.java:70)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:47)
	at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor.intercept(RolesAllowedInterceptor.java:29)
	at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:44)
	at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_RolesAllowedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl_Subclass.updateVariables(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl_ClientProxy.updateVariables(Unknown Source)
	at io.hyperfoil.tools.horreum.api.internal.services.AlertingService$quarkusrestinvoker$updateVariables_38a638985bf08b41bf5f0583f1ba7ef6d804f802.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

 Should be using `merge` instead of `persist` when persisting a *detached* entity.

**To Reproduce**

**Version**

```
0.10.7
```

**Java**

What is the version of Java ?

```
17
```

### PR DESCRIPTION
**Pull request by whitingjr**
## Fixes Issue

 fixes #1124  #1379 

## Changes proposed

[x] - Replace entity associated with session

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

File: horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java [hunk 1]
```diff
@@ -776,6 +765,38 @@ public void testFindLastDatapoints(TestInfo info) throws IOException {
...
+      Variable throughput = new Variable();
+      throughput.id = -1;
+      throughput.testId = test.id;
+      throughput.name = "throughput";
+      throughput.labels = labels;
+      throughput.changeDetection = cdSet;
+
+      variables.add(throughput);
+
+      updateVariables(test.id, variables);//update
```
Comment (stalep) [inline horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java:797]: can we add an assertion here as well to make sure the variables have been updated?

Comment (whitingjr) [reply horreum-backend/src/test/java/io/hyperfoil/tools/horreum/svc/AlertingServiceTest.java:797]: sure
