### PR TITLE
fix #1484 remove final pattern check

### LINKED ISSUE #1484: Unable to parse start time
Previously working upload have started failing with the following error message:

`Cannot parse start time from 2024-03-13T21:18:10.878423-04:00 ($.start_time)`

Jobs that adhered to this datetime format were previsouly imported, e.g.:

`"start_time": "2024-03-11T22:16:24.302655-04:00"`

This change was likely introduced here: https://github.com/Hyperfoil/Horreum/pull/1322/files#diff-0a2af3ce63d006af3ce2a9893563d8cc63de6e2c648d8b35af1a6c26e7ecb98f

### PR DESCRIPTION
**Pull request by willr3**
fix #1484

### CODE REVIEW

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java [hunk 1]
```diff
@@ -649,13 +649,11 @@ public static Instant toInstant(Object time) {
...
-            try {
-               return ZonedDateTime.parse(str, DateTimeFormatter.ISO_DATE_TIME).toInstant();
-            } catch (DateTimeParseException e) {
-               e.printStackTrace();
-            }
+         //ISO_DATE_TIME, do not verify with pattern because multipel patterns are possible
+         try {
+            return ZonedDateTime.parse(str, DateTimeFormatter.ISO_DATE_TIME).toInstant();
+         } catch (DateTimeParseException e) {
+            e.printStackTrace();
```
Comment (johnaohara) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java:656]: This should be logged with the logger

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java [hunk 2]
```diff
@@ -649,13 +649,11 @@ public static Instant toInstant(Object time) {
...
             str=str+"Z";
          }
-         //ISO_DATE_TIME
-         if(str.matches("\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:Z|[+\\-]\\d{2}:\\d{2})")){
-            try {
-               return ZonedDateTime.parse(str, DateTimeFormatter.ISO_DATE_TIME).toInstant();
-            } catch (DateTimeParseException e) {
-               e.printStackTrace();
-            }
+         //ISO_DATE_TIME, do not verify with pattern because multipel patterns are possible
```
Comment (johnaohara) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/Util.java:652]:
```suggestion
         //ISO_DATE_TIME, do not verify with pattern because multiple patterns are possible
```

**Review by johnaohara — CHANGES_REQUESTED** [review]
We should log the `DateTimeParseException` exception with the defined logger rather than using `printStackTrace()`
