### PR TITLE
fix #1402 avoid default limit and page

### LINKED ISSUE #1402: Full list of folders not displayed on Changes view
**Describe the bug**

The complete list of folders is not being displayed in the Changes view in the current master branch;

Stable;

Screenshot from 2024-03-04 09-34-44

Master;

Screenshot from 2024-03-04 09-34-36

### PR DESCRIPTION
**Pull request by willr3**
closes #1402

### CODE REVIEW

File: horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java [hunk 1]
```diff
@@ -321,7 +321,9 @@ public TestListing summary(String roles, String folder, Integer limit, Integer p
          testSql.append(" WHERE COALESCE(folder, '') = COALESCE((?1)::::text, '')");
          Roles.addRolesSql(identity, "test", testSql, roles, 2, " AND");
       }
-      Util.addPaging(testSql, limit, page, "test.name", direction);
+      if( limit > 0 && page > 0 ) {
```
Comment (johnaohara) [inline horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java:324]: is `page` 0-indexed?

Comment (willr3) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java:324]: Default in the annotation is 1

Comment (johnaohara) [reply horreum-backend/src/main/java/io/hyperfoil/tools/horreum/svc/TestServiceImpl.java:324]: ok, as long as we can just return the first page
